### ISSUE TITLE
Housekeeping is here for .git 

### ISSUE THREAD

**Issue by vipulgupta2048** [asetalias/asetalias.github.io#128]
As a repository becomes older and older. The number of commits, branches, assets stored takes a toll on git. The biggest strength of git is also its biggest flaw. It remembers everything.

Well, only until one authorizes it to forget. 

**Task**
Follow the guide to reduce the size of .git folder in the repository (Which is now 22.7 mb) to somewhat lesser than that.

To help here are some great guides [1](https://git-scm.com/book/en/v2/Git-Internals-Maintenance-and-Data-Recovery), [2](https://github.com/18F/C2/issues/439#issue-92543693),

**Comment by Sc0rpi0n101** [comment]
Wait, how is this a good first issue?
For people who don't have much experience with Open-source & prob git and are looking for thier first issue, housekeeping git might not be the right thing to start on xD.

**Comment by vipulgupta2048** [comment]
I agree, I had a perspective of someone be able to learn more about git, amd how it works internally by doing this task. Reassessing, yes definitely not a good first issue

**Comment by nmay231** [comment]
Well, I was just taking a look to see how reasonable it would be to work on this and I don't know if it is honestly. It looks like most of the large size is due to existing/previous versions of existing images.

I just made a fresh clone, then ran

```bash
git verify-pack -v .git/objects/pack/pack-a0a3d6c2cbc90fce318270c3aaad78c9af0c293e.idx | sort -k 3 -n | cut -c-41 | tail -150 >> tmp.txt
```

to get the shas of the largest 150 commits. Then to get the file names,

```bash
git rev-list --objects --all | grep -f tmp.txt
```

It looks like most of them are presently existing files in `images/` and `fonts/`. And while I wish I could run a command to find the exact files that could safely be removed from history, I'm not *that* skilled with git.

My suggestion, if low first-clone-size is at all a priority, you should gitignore all images *and* from previous commits, and then just store your images somewhere else other than github. Though, it seems like that's more work than it's worth. It is only the first clone after all.

Just FYI :+1:
