### ISSUE TITLE
[Redesign] Change the ASET ALiAS Logo to the original one on the website.

### ISSUE THREAD

**Issue by TanyaaCJain** [asetalias/asetalias.github.io#224]
**Describe the bug**
The current logo displayed on the website does not match the original one used for ASET ALiAS branding on all platforms.

**To Reproduce**
1. Go to the [website homepage](https://asetalias.in)
2. Look at the logo.

**Expected behavior**
The logo is expected to match with the branding of ASET ALiAS, which can be found at [ALiAS Logos](https://github.com/asetalias/Logistics-and-Event-Contributions/tree/master/AliasLogos). 

The current animation on the logo looks good. If the same behaviour could be brought into effect with the original logo, then it would be appreciated.

**Comment by sksuryan** [comment]
@TanyaaCJain I was the one who actually created that logo. It's animated because it's an SVG, for the original logo to be animated, we would need an SVG of it. Either since the current logo on the website is an SVG already it could be scaled for other platforms or the original logo could be found in previous commits and could be used instead.

**Comment by TanyaaCJain** [comment]
@sksuryan Thank you for following up! The original logo was created by @parthsharma2 who has been contacted to send us its SVG file. It is the goto option as it seems that the website originally used  .PNG file logo as you can see it in this [commit](https://github.com/asetalias/asetalias.github.io/pull/6/files?file-filters%5B%5D=.png&short_path=706ff17#diff-f123c3c8de676728340785356023b87e). Let's wait for @parthsharma2 to respond and we will take action accordingly.
