### ISSUE TITLE
Moving to Dynamic Website -> Using Django/Flask framework

### ISSUE THREAD

**Issue by aniketmaithani** [asetalias/asetalias.github.io#27]
As per the conversation on the Telegram group the point came out that we should have a dynamic website. Since most of the students are interested in learning Django/Python from scratch it would be a great experience for them to have a hands-on a real project. 

Hence, I am opening this thread so that each one of you can put in your respective view(s). 

cc @bhanuvrat @arcolife @mysticTot @thisisayush @parthsharma2

**Comment by parthsharma2** [comment]
Totally up for this project👍

**Comment by aniketmaithani** [comment]
@parthsharma2 thanks for you valuable feedback

**Comment by arcolife** [comment]
@aniketmaithani so IIUC we need to have MVT/MVC in place, instead of the static pages? and by  developing this 'dynamic' website together, we hope to end up with people having a hands-on experience and also a finished product simultaneously? if yes, sounds great! :clinking_glasses: :

perhaps we might wanna take a look at https://github.com/crowdresearch/crowdsource-platform which was developed using the same strategy in mind. They also have a good labeling system in place. https://github.com/crowdresearch/crowdsource-platform/labels

**Comment by thisisayush** [comment]
Discussion moved to referenced issue #35 ! Closing this issue
